### ISSUE TITLE
Editable annotation crashes application

### ISSUE THREAD

**Issue by Langriklol** [baraja-core/cms#46]
Version: latest

### Bug Description
When running `composer update` or `composer dump` the command appropriate for running application crashes due to missing import. 
<img width="698" alt="image" src="https://user-images.githubusercontent.com/20239181/129347969-89705da7-a402-4dc4-8d0e-ec64dfd3ca28.png">

### Steps To Reproduce
Run `composer dump` on latest version of package

### Expected Behavior
Not to crash application

### Possible Solution
Maybe consider refactoring as PHP attribute

**Comment by janbarasek** [comment]
Solved in `baraja-core/quick-edit-api` version `^2.1`.

Can you test it?

Source: https://github.com/baraja-core/quick-edit-api/commit/a0e1c165b219d26b6d9e41af229c4cbec66e2e07
