### ISSUE TITLE
Nenačte se přihlašovací stránka adminu

### ISSUE THREAD

**Issue by stralkaj** [baraja-core/cms#64]
Vyskytuje se u mě na všech adminech kromě cz. Přesměrovává to https://www.example.sk/admin/assets/css/bootstrap-vue-2-21-2.min.css na https://www.example.sk/admin

**Comment by janbarasek** [comment]
Šlo o chybu na straně aplikace. Je potřeba nakonfigurovat základní ENV proměnné v databázi.
