### ISSUE TITLE
Zprovoznit translator na frontendu

### ISSUE THREAD

**Issue by stralkaj** [baraja-core/cms#65]
- Jak jsem vyházel přebytečné knihovny, tak přestal fungovat translator na frontendu
- Prosím citlivě to zprovniznit, tzn. přidat jen nezbytné knihovny, ověřit aby tam nebyly 2x a aby se načítaly jen pro adminy, ne pro návštěvníky

**Comment by janbarasek** [comment]
Nepatří do tohoto projektu.
